Repository DhanushNehru/Ultimate-Tech-Jobs, pull requests merged in 2023-10, with the labels that each got.

#3 added the readme file
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#6 Added Hired website to the list
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#8 Added Simply Hired Job Site to the list
  README.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#12 Add: New job channel to Telegram Job Channel
  README.md
Labels: hacktoberfest, hacktoberfest-accepted
